"""
seed_local.py - Seeds the Wakeeli local SQLite database with test listings and agents.
Uses the app's own SQLAlchemy engine so it works with whatever DB is configured.
Run from: /home/claw/claudeclaw/workspace/Wakeeli/backend/
  python3 seed_local.py
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

os.environ.setdefault("DATABASE_URL", "sqlite:///./wakeeli.db")
os.environ.setdefault("OPENAI_API_KEY", "placeholder")

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
from app.models import Listing, Agent, Base

DB_URL = os.environ.get("DATABASE_URL", "sqlite:///./wakeeli.db")

if DB_URL.startswith("sqlite"):
    engine = create_engine(DB_URL, connect_args={"check_same_thread": False})
else:
    engine = create_engine(DB_URL)

Base.metadata.create_all(bind=engine)
Session = sessionmaker(bind=engine)
session = Session()

print(f"Connected to: {DB_URL}")
print("Clearing existing listings and agents...")

session.query(Listing).delete()
session.query(Agent).delete()
session.commit()

listings = [
    Listing(
        listing_type="rent",
        property_type="Apartment",
        property_id="WK-R-001",
        title="Modern 2BR Apartment in Achrafieh",
        category="Residential",
        city="Beirut",
        area="Achrafieh",
        building_name="Gemmayzeh Heights",
        bedrooms=2,
        bathrooms=2,
        built_up_area=120.0,
        floor_number=4,
        parking="1",
        property_age="5-10",
        furnishing="Furnished",
        view="City",
        condition="Ready",
        rent_price=1200.0,
        rental_duration="Yearly",
        security_deposit=2400.0,
        negotiable=True,
        description="Bright 2-bedroom in the heart of Achrafieh. Fully furnished, open kitchen, city views. Walking distance to restaurants and cafes.",
        is_available=True,
    ),
    Listing(
        listing_type="rent",
        property_type="Apartment",
        property_id="WK-R-002",
        title="Cozy 1BR in Hamra Near AUB",
        category="Residential",
        city="Beirut",
        area="Hamra",
        bedrooms=1,
        bathrooms=1,
        built_up_area=75.0,
        floor_number=2,
        parking="None",
        property_age="10+",
        furnishing="Semi-Furnished",
        view="City",
        condition="Ready",
        rent_price=700.0,
        rental_duration="Yearly",
        security_deposit=1400.0,
        negotiable=False,
        description="Comfortable 1-bedroom steps from AUB main gate. Semi-furnished with AC and built-in wardrobes. Ideal for students or professionals.",
        is_available=True,
    ),
    Listing(
        listing_type="rent",
        property_type="Apartment",
        property_id="WK-R-003",
        title="Spacious 3BR in Verdun with Parking",
        category="Residential",
        city="Beirut",
        area="Verdun",
        building_name="Verdun Plaza",
        bedrooms=3,
        bathrooms=2,
        built_up_area=185.0,
        floor_number=6,
        parking="Covered",
        property_age="5-10",
        furnishing="Unfurnished",
        view="City",
        condition="Ready",
        rent_price=1800.0,
        rental_duration="Yearly",
        security_deposit=3600.0,
        negotiable=True,
        description="Large 3-bedroom in Verdun with covered parking and generator. Unfurnished so you can make it your own. High floor with balcony.",
        is_available=True,
    ),
    Listing(
        listing_type="rent",
        property_type="Apartment",
        property_id="WK-R-004",
        title="Furnished Studio in Ras Beirut",
        category="Residential",
        city="Beirut",
        area="Ras Beirut",
        bedrooms=0,
        bathrooms=1,
        built_up_area=45.0,
        floor_number=3,
        parking="None",
        property_age="5-10",
        furnishing="Furnished",
        view="Open",
        condition="Ready",
        rent_price=500.0,
        rental_duration="Monthly",
        security_deposit=1000.0,
        negotiable=False,
        description="Compact furnished studio in Ras Beirut. Includes kitchenette and AC. Perfect for short-term stay near AUBMC or the Corniche.",
        is_available=True,
    ),
    Listing(
        listing_type="rent",
        property_type="Apartment",
        property_id="WK-R-005",
        title="Sea View 2BR Apartment in Jounieh",
        category="Residential",
        city="Jounieh",
        area="Jounieh",
        building_name="Marina Towers",
        bedrooms=2,
        bathrooms=2,
        built_up_area=135.0,
        floor_number=8,
        parking="1",
        property_age="1-5",
        furnishing="Furnished",
        view="Sea",
        condition="Ready",
        rent_price=1400.0,
        rental_duration="Yearly",
        security_deposit=2800.0,
        negotiable=True,
        description="Sea-view apartment in Jounieh Marina. Fully furnished, marble floors, wraparound balcony with direct bay views.",
        is_available=True,
    ),
    Listing(
        listing_type="rent",
        property_type="Villa",
        property_id="WK-R-006",
        title="Mountain Villa for Rent in Broummana",
        category="Residential",
        city="Broummana",
        area="Broummana",
        bedrooms=4,
        bathrooms=3,
        built_up_area=300.0,
        plot_area=500.0,
        parking="2",
        property_age="10+",
        furnishing="Furnished",
        view="Mountain",
        condition="Ready",
        rent_price=3000.0,
        rental_duration="Yearly",
        security_deposit=6000.0,
        negotiable=True,
        description="Classic Lebanese stone villa in Broummana with private garden and mountain views. 4 bedrooms, fully furnished, outdoor dining area. Generator and water tank included.",
        is_available=True,
    ),
    Listing(
        listing_type="rent",
        property_type="Apartment",
        property_id="WK-R-007",
        title="2BR Apartment in Batroun Sea District",
        category="Residential",
        city="Batroun",
        area="Batroun",
        building_name="Batroun Seaview Residences",
        bedrooms=2,
        bathrooms=1,
        built_up_area=110.0,
        floor_number=2,
        parking="1",
        property_age="1-5",
        furnishing="Semi-Furnished",
        view="Sea",
        condition="Ready",
        rent_price=900.0,
        rental_duration="Yearly",
        security_deposit=1800.0,
        negotiable=False,
        description="Coastal living in Batroun. 2 bedrooms, sea views, 5 minutes to the old Phoenician wall and beach clubs.",
        is_available=True,
    ),
    Listing(
        listing_type="rent",
        property_type="Apartment",
        property_id="WK-R-008",
        title="3BR Family Apartment in Jbeil",
        category="Residential",
        city="Jbeil",
        area="Jbeil",
        bedrooms=3,
        bathrooms=2,
        built_up_area=150.0,
        floor_number=1,
        parking="1",
        property_age="5-10",
        furnishing="Semi-Furnished",
        view="Open",
        condition="Ready",
        rent_price=1100.0,
        rental_duration="Yearly",
        security_deposit=2200.0,
        negotiable=False,
        description="Generous 3-bedroom near Byblos old town. Semi-furnished, large terrace, quiet street with highway access.",
        is_available=True,
    ),
    Listing(
        listing_type="rent",
        property_type="Apartment",
        property_id="WK-R-009",
        title="Budget 1BR in Hamra",
        category="Residential",
        city="Beirut",
        area="Hamra",
        bedrooms=1,
        bathrooms=1,
        built_up_area=65.0,
        floor_number=3,
        parking="None",
        property_age="10+",
        furnishing="Unfurnished",
        view="City",
        condition="Ready",
        rent_price=550.0,
        rental_duration="Yearly",
        security_deposit=1100.0,
        negotiable=True,
        description="Affordable unfurnished 1-bedroom in Hamra. Clean building with elevator and generator. Ideal for young professionals.",
        is_available=True,
    ),
    Listing(
        listing_type="rent",
        property_type="Apartment",
        property_id="WK-R-010",
        title="4BR Family Home in Verdun",
        category="Residential",
        city="Beirut",
        area="Verdun",
        bedrooms=4,
        bathrooms=3,
        built_up_area=250.0,
        floor_number=5,
        parking="Covered",
        property_age="5-10",
        furnishing="Unfurnished",
        view="City",
        condition="Ready",
        rent_price=2800.0,
        rental_duration="Yearly",
        security_deposit=5600.0,
        negotiable=True,
        description="Premium 4-bedroom family apartment in Verdun. 2 covered parking spots, 24h concierge, full generator. Schools and embassies nearby.",
        is_available=True,
    ),
    Listing(
        listing_type="buy",
        property_type="Apartment",
        property_id="WK-S-001",
        title="Luxury 3BR for Sale in Achrafieh",
        category="Residential",
        city="Beirut",
        area="Achrafieh",
        building_name="Sodeco Square Residences",
        bedrooms=3,
        bathrooms=3,
        built_up_area=210.0,
        floor_number=9,
        parking="Covered",
        property_age="1-5",
        furnishing="Unfurnished",
        view="City",
        condition="Ready",
        sale_price=650000.0,
        negotiable=True,
        description="Premium 3-bedroom in Sodeco with Italian kitchen, floor-to-ceiling windows, rooftop pool, and covered parking. Title deed in USD.",
        is_available=True,
    ),
    Listing(
        listing_type="buy",
        property_type="Apartment",
        property_id="WK-S-002",
        title="Investment Apartment in Hamra",
        category="Residential",
        city="Beirut",
        area="Hamra",
        bedrooms=2,
        bathrooms=1,
        built_up_area=100.0,
        floor_number=5,
        parking="1",
        property_age="10+",
        furnishing="Unfurnished",
        view="City",
        condition="Needs Renovation",
        sale_price=175000.0,
        negotiable=True,
        description="Good bones in prime Hamra. 2-bedroom priced to reflect renovation needed. Excellent rental yield potential. Clean title deed.",
        is_available=True,
    ),
    Listing(
        listing_type="buy",
        property_type="Apartment",
        property_id="WK-S-003",
        title="Panoramic Sea View Apartment in Jounieh",
        category="Residential",
        city="Jounieh",
        area="Jounieh",
        building_name="Bay Tower",
        bedrooms=3,
        bathrooms=2,
        built_up_area=165.0,
        floor_number=12,
        parking="Covered",
        property_age="5-10",
        furnishing="Unfurnished",
        view="Sea",
        condition="Ready",
        sale_price=420000.0,
        negotiable=False,
        description="High-floor 3-bedroom with panoramic Jounieh bay views. Marble throughout, large wraparound terrace. Building has 24/7 security and rooftop pool.",
        is_available=True,
    ),
    Listing(
        listing_type="buy",
        property_type="Villa",
        property_id="WK-S-004",
        title="Stone Villa for Sale in Beit Mery",
        category="Residential",
        city="Beit Mery",
        area="Beit Mery",
        bedrooms=4,
        bathrooms=4,
        built_up_area=450.0,
        plot_area=800.0,
        parking="2",
        property_age="10+",
        furnishing="Unfurnished",
        view="Mountain",
        condition="Ready",
        sale_price=800000.0,
        negotiable=True,
        description="Magnificent stone villa in Beit Mery on 800 sqm. 4 bedrooms, wine cellar, private pool. Panoramic views over Beirut and the sea.",
        is_available=True,
    ),
    Listing(
        listing_type="buy",
        property_type="Apartment",
        property_id="WK-S-005",
        title="Brand New 2BR in Jbeil",
        category="Residential",
        city="Jbeil",
        area="Jbeil",
        building_name="Byblos Bay Residences",
        bedrooms=2,
        bathrooms=2,
        built_up_area=130.0,
        floor_number=3,
        parking="1",
        property_age="1-5",
        furnishing="Unfurnished",
        view="Sea",
        condition="Ready",
        sale_price=280000.0,
        negotiable=False,
        description="Fresh delivery in Byblos. 2 bedrooms with sea views, quality finishes. Walking distance to Byblos old souk and marina.",
        is_available=True,
    ),
    Listing(
        listing_type="buy",
        property_type="Apartment",
        property_id="WK-S-006",
        title="Affordable 1BR in Verdun",
        category="Residential",
        city="Beirut",
        area="Verdun",
        bedrooms=1,
        bathrooms=1,
        built_up_area=80.0,
        floor_number=2,
        parking="None",
        property_age="10+",
        furnishing="Unfurnished",
        view="Open",
        condition="Ready",
        sale_price=150000.0,
        negotiable=True,
        description="Entry-level apartment in a well-maintained Verdun building. 1 bedroom, clean and move-in ready. Good first purchase or rental investment.",
        is_available=True,
    ),
    Listing(
        listing_type="buy",
        property_type="Villa",
        property_id="WK-S-007",
        title="Modern Villa in Broummana with Pool",
        category="Residential",
        city="Broummana",
        area="Broummana",
        bedrooms=3,
        bathrooms=3,
        built_up_area=320.0,
        plot_area=600.0,
        parking="2",
        property_age="1-5",
        furnishing="Unfurnished",
        view="Mountain",
        condition="Ready",
        sale_price=590000.0,
        negotiable=True,
        description="Contemporary villa in Broummana with private pool, landscaped garden, smart home system, and rooftop terrace with Beirut and sea views.",
        is_available=True,
    ),
    Listing(
        listing_type="buy",
        property_type="Apartment",
        property_id="WK-S-008",
        title="High-Floor 3BR in Ras Beirut",
        category="Residential",
        city="Beirut",
        area="Ras Beirut",
        building_name="Corniche Tower",
        bedrooms=3,
        bathrooms=2,
        built_up_area=190.0,
        floor_number=14,
        parking="Covered",
        property_age="5-10",
        furnishing="Unfurnished",
        view="Sea",
        condition="Ready",
        sale_price=520000.0,
        negotiable=True,
        description="High-floor 3-bedroom with direct sea views over the Corniche. Large balcony, covered parking, building generator and security. Great for families or expats.",
        is_available=True,
    ),
    Listing(
        listing_type="buy",
        property_type="Apartment",
        property_id="WK-S-009",
        title="Renovated 2BR for Sale in Ras Beirut",
        category="Residential",
        city="Beirut",
        area="Ras Beirut",
        bedrooms=2,
        bathrooms=2,
        built_up_area=130.0,
        floor_number=6,
        parking="Covered",
        property_age="10+",
        furnishing="Unfurnished",
        view="Sea",
        condition="Ready",
        sale_price=240000.0,
        negotiable=True,
        description="Fully renovated 2-bedroom in Ras Beirut with partial sea view. New plumbing and electrical, open plan kitchen, 2 covered parking. Ideal for end-users or investors.",
        is_available=True,
    ),
    Listing(
        listing_type="buy",
        property_type="Villa",
        property_id="WK-S-010",
        title="Hilltop Villa with Sea View in Batroun",
        category="Residential",
        city="Batroun",
        area="Kfar Aabida",
        bedrooms=3,
        bathrooms=2,
        built_up_area=220.0,
        plot_area=400.0,
        parking="2",
        property_age="1-5",
        furnishing="Unfurnished",
        view="Sea",
        condition="Ready",
        sale_price=280000.0,
        negotiable=True,
        description="Standalone hilltop villa near Batroun with spectacular sea views. 3 bedrooms, large terrace, private garden. Solar panels and water tanks installed.",
        is_available=True,
    ),
]

agents = [
    Agent(
        name="Rania Khalil",
        phone="+961 71 234 567",
        email="rania.khalil@wakeeli.com",
        territories=["Achrafieh", "Gemmayzeh", "Mar Mikhael", "Ras Beirut"],
        specialties=["rentals", "sales", "luxury"],
        priority=1,
        is_active=True,
    ),
    Agent(
        name="Karim Nassar",
        phone="+961 70 345 678",
        email="karim.nassar@wakeeli.com",
        territories=["Jounieh", "Jbeil", "Batroun", "Broummana", "Beit Mery"],
        specialties=["sales", "luxury", "villas"],
        priority=1,
        is_active=True,
    ),
    Agent(
        name="Lara Haddad",
        phone="+961 76 456 789",
        email="lara.haddad@wakeeli.com",
        territories=["Hamra", "Verdun", "Ras Beirut"],
        specialties=["rentals", "sales"],
        priority=2,
        is_active=True,
    ),
    Agent(
        name="Georges Abou Zeid",
        phone="+961 78 567 890",
        email="georges.abouzeid@wakeeli.com",
        territories=["Broummana", "Beit Mery", "Ain Saadeh", "Bikfaya"],
        specialties=["sales", "villas", "land"],
        priority=2,
        is_active=True,
    ),
]

for listing in listings:
    session.add(listing)

for agent in agents:
    session.add(agent)

session.commit()

listing_count = session.query(Listing).count()
agent_count = session.query(Agent).count()

rentals = session.query(Listing).filter(Listing.listing_type == "rent").count()
sales = session.query(Listing).filter(Listing.listing_type == "buy").count()

print(f"\nSeed complete!")
print(f"  Listings: {listing_count} (Rentals: {rentals}, For Sale: {sales})")
print(f"  Agents:   {agent_count}")

session.close()
