"""initial schema with lead model extension

Revision ID: 6ee14fe54098
Revises: 
Create Date: 2026-06-09 16:29:09.588606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee14fe54098'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('budget_min', sa.Float(), nullable=True))
    op.add_column('conversations', sa.Column('budget_max', sa.Float(), nullable=True))
    op.add_column('conversations', sa.Column('timeline', sa.String(length=100), nullable=True))
    op.add_column('conversations', sa.Column('urgency', sa.String(length=50), nullable=True))
    op.add_column('listings', sa.Column('maids_room', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('balconies', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('electricity_24_7', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('elevator', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('concierge', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('storage', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('ac_heating', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('generator', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'notes')
    op.drop_column('listings', 'generator')
    op.drop_column('listings', 'ac_heating')
    op.drop_column('listings', 'storage')
    op.drop_column('listings', 'concierge')
    op.drop_column('listings', 'elevator')
    op.drop_column('listings', 'electricity_24_7')
    op.drop_column('listings', 'balconies')
    op.drop_column('listings', 'maids_room')
    op.drop_column('conversations', 'urgency')
    op.drop_column('conversations', 'timeline')
    op.drop_column('conversations', 'budget_max')
    op.drop_column('conversations', 'budget_min')
    # ### end Alembic commands ###
